version: '3'

services:
  crawlspeed:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: crawlspeed
    ports:
      - '8092:3001'
    volumes:
      - ../logs:/usr/src/app/logs
    restart: 'always'
